Filmorate v1.0
dimabakinec/java-filmorate pull request #3
Opened 2023-03-02 10:00 UTC by dimabakinec

2023-03-03 11:27 UTC, alexache requested changes

2023-03-03 11:27 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public static boolean validate(Film film) throws ValidationException {
Можно бы постараться сделать валидации через аннотации на модели

2023-03-03 11:27 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    }
Немного запутался, что есть тест на контроллер пользователей, но не на контроллер фильмов

2023-03-03 12:11 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    protected final HashMap<Integer, Film> films = new HashMap<>();
protected final Map<Integer, User> users = new HashMap<>();

изменил, в UserController тоже

2023-03-03 12:19 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            log.info("Login is instead of name");
убрал логирование

2023-03-06 09:56 UTC, dimabakinec commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    }
удалил, нужны ведь только тесты на валидаторы ?!

2023-03-06 09:57 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            log.info("Login is instead of name");
переделал

2023-03-06 12:12 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public static boolean validate(Film film) throws ValidationException {
все еще актуально эта ошибка после остальных изменений?

2023-03-06 12:28 UTC, dimabakinec commented
исправил

2023-03-06 16:16 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    }
да, в данном спринте говорится только о тестах валидации

2023-03-06 16:30 UTC, alexache requested changes

2023-03-06 16:30 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createUser(@RequestBody @Validated User user) {
@Valid?

2023-03-06 16:30 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +//    @Null
Отчего они закомментированны?

2023-03-06 16:58 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info(film.toString());
переделал

2023-03-06 17:42 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public static boolean validate(Film film) throws ValidationException {
поправил, все работает

2023-03-06 17:43 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +//    @Null
поправил

2023-03-06 21:03 UTC, alexache approved these changes

2023-03-06 21:03 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        UserValidator.validate(user);
Все равно немного не понимаю подхода - у тебя есть как аннотации на классе, так и отдельный класс валидатора. Зачем этот класс валидатора, если он дублирует аннотации?

2023-03-07 08:23 UTC, merged