Sprint 10, Filmorate v1.0
dimabakinec/java-filmorate pull request #4
Opened 2023-03-20 10:34 UTC by dimabakinec

2023-03-20 20:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.filmStorage.addNewFilm(film);
Это нарушение инкапсуляции. Нужен соответствующий метод в сервисе для добавления фильма

2023-03-20 20:02 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film addOrDeleteLikeToFilm(long filmId, long userId, String typeOperation) {
Очень странно из енама делать строку, а потом на нем switch-case, почему бы не оставить енам как он был в контроллере?

2023-03-20 20:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    }
Не хватает пустых строк между методами

2023-03-20 20:08 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> findMostPopularFilms(String countFilms) {
Почему на вход строка,  а не число?

2023-03-20 20:09 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            List<Long> firstUserFriendsList = firstUser.getFriendsIdsSet().stream().collect(Collectors.toList());
Зачем из Set делать List?

2023-03-20 20:17 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController filmController;
Модификаторы доступа

2023-03-21 07:45 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    boolean validateName(Film film) {
добавлены модифакторы доступа "public"

2023-03-21 07:48 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    }
пробелы добавлены

2023-03-21 07:51 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    User addNewUser(@RequestBody User user) {
добавлены модификаторы доступа

2023-03-21 08:40 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Film addNewFilm(@RequestBody Film film) {
добавлены модификаторы доступа "public"

2023-03-21 09:23 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.filmStorage.addNewFilm(film);
метод добавен

2023-03-21 09:23 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.filmStorage.updateFilm(film);
метод добавлен

2023-03-21 09:24 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    final String pathForFilmLike = "/{id}/like/{userId}";
переменная pathForFilmLike удалена

2023-03-21 09:57 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> findMostPopularFilms(String countFilms) {
исправлено на int

2023-03-22 12:14 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            List<Long> firstUserFriendsList = firstUser.getFriendsIdsSet().stream().collect(Collectors.toList());
метод getMutualFriends исправлен

2023-03-22 12:14 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            for (long firstFriendFriendId : firstUserFriendsList) {
метод getMutualFriends исправлен

2023-03-22 12:14 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            for (User user : userStorage.getUsers().values()) {
метод getMutualFriends исправлен

2023-03-22 18:08 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film addOrDeleteLikeToFilm(long filmId, long userId, String typeOperation) {
исправлено

2023-03-22 18:48 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    boolean validateEmail(User user) {
созданы отдельные классы для валидации

2023-03-23 17:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.filmStorage.addNewFilm(film);
Не вижу, а где этот метод используется в контроллере?

2023-03-23 17:59 UTC, alexache requested changes

2023-03-24 08:03 UTC, closed without merging