Add database
dimabakinec/java-filmorate pull request #6
Opened 2023-04-13 13:43 UTC by dimabakinec

2023-04-14 17:37 UTC, alexache requested changes

2023-04-14 17:37 UTC, alexache commented on src/main/resources/schema.sql
> +INSERT INTO MPA_RATINGS(name) VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');
Данные лучше отдельным скриптом

2023-04-14 17:37 UTC, alexache commented on src/main/resources/schema.sql
> +ALTER TABLE "PUBLIC"."LIKES" ADD CONSTRAINT IF NOT EXISTS "LIKES_PK" PRIMARY KEY("ID");
Может как-то вся связанное с одной сущностью писать вместе в одном create table? Немного сложно следить за логикой в разных частях скрипта?

2023-04-14 17:37 UTC, alexache commented on src/main/resources/application.properties
> -#logging.level.ru.yandex.practicum.filmorate.controller=debug
Много закомментированного кода, и не вижу настроек базы данных

2023-04-14 17:37 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    .mpa(findMpaById(rs.getInt("mpa_rating_id")))
Это нужно получать джоином на таблицу мпа в селекте фильма

2023-04-14 17:37 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                String sqlQuery = "insert into film_genres(film_id, genre_id) " +
Запросы к базе в цикле - это плохо, нужны батч операции

2023-04-14 17:37 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    private Film makeFilm(ResultSet rs) throws SQLException {
А для чего в каких-то методах этот метод формирования фильмов используется, а в каких то нет

2023-04-14 17:37 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                .genres(findGenresByFilmId(rs.getInt("id")));
Это запрос к базе в цикле (метод makeFilm вызывается в цикле, а значет нельзя делать запросы к базе)

2023-04-14 17:37 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sqlQuery = "select genres.*\n" +
Работу с жанрами и с мпа лучше выносить в отдельный сторадж

2023-04-14 17:37 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/MpaRating.java
> +public class MpaRating {
А для чего два класса про МПА?

2023-04-14 17:37 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Map<String, Object> toMap() {
А для чего такой метод?

2023-04-14 17:39 UTC, alexache commented
Забыл еше один момент уточнить - нужна схема базы данных в виде диаграммы и ссылка на нее в ридми

2023-04-15 15:32 UTC, dimabakinec commented on src/main/resources/application.properties
> -#logging.level.ru.yandex.practicum.filmorate.controller=debug
поправил, настройки были не знаю почему не попали в реквест

2023-04-15 16:35 UTC, dimabakinec commented on src/main/resources/schema.sql
> +ALTER TABLE "PUBLIC"."LIKES" ADD CONSTRAINT IF NOT EXISTS "LIKES_PK" PRIMARY KEY("ID");
исправлено

2023-04-15 16:35 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    .mpa(findMpaById(rs.getInt("mpa_rating_id")))
переделал

2023-04-15 16:35 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                String sqlQuery = "insert into film_genres(film_id, genre_id) " +
переделал

2023-04-15 16:36 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    private Film makeFilm(ResultSet rs) throws SQLException {
переделал

2023-04-15 16:36 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                .genres(findGenresByFilmId(rs.getInt("id")));
исправлено

2023-04-15 16:36 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sqlQuery = "select genres.*\n" +
вынес в отдельные стораджи

2023-04-15 16:37 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/model/MpaRating.java
> +public class MpaRating {
исправлено

2023-04-15 16:37 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Map<String, Object> toMap() {
переделал

2023-04-15 16:40 UTC, dimabakinec commented on src/main/resources/schema.sql
> +INSERT INTO MPA_RATINGS(name) VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');
вынес в отдельный файл data.sql

2023-04-15 16:52 UTC, dimabakinec commented
не могу разобраться новый ПР делать или этот? ругается что в бренче на ПР отправляется файл checkstyle.xml но я его удалил из всех веток

2023-04-15 22:50 UTC, alexache requested changes

2023-04-15 22:50 UTC, alexache commented on src/main/resources/application.properties
> +spring.sql.init.mode=alwaysspring.datasource.url=jdbc:h2:file:./db/filmoratespring.datasource.driverClassName=org.h2.Driverspring.datasource.username=saspring.datasource.password=password
Что-то странно отображается, может быть есть проблема с переносами строк?

2023-04-15 22:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/FilmMapper.java
> +        List<Genre> genres = listGenresByFilms.getOrDefault(rs.getLong("film_id"), new ArrayList<>());
И List, и Set - какая-та странная комбинация

2023-04-15 22:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        return find(data.getId());
А зачем требуется поиск в конце апдейта?

2023-04-15 22:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public Map<Long, List<Genre>> getGenreByFilm() {
А зачем нужен метод получения всех жанров всех фильмов? Более логичен метод получения жанров по списку фильмов (или одному фильму)

2023-04-15 22:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        final String sqlAddLike = "UPDATE films SET count_likes = count_likes + 1 WHERE film_id=?";
(опционально) Эти ручные + - для подсчета количества лайков выглядят не очень надежно, можно ведь всегда одним запросом получить количество лайков для конкретного фильма на основен таблицы с лайками?

2023-04-15 22:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        Map<Long, List<Genre>> listGenresByFilms = genreDbStorage.getGenreByFilm();
Лучше запрашивать жанры по фильмам, которые мы получили нежели сохранять все жанры всех фильмов в эту мапу

2023-04-15 22:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        Map<Long, List<Genre>> listGenresByFilms = genreDbStorage.getGenreByFilm();
Похожий комментарий есть в других стораджах и у getGenreByFilm

2023-04-15 22:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        final String sql = "INSERT INTO popular_films (film_id, user_id) VALUES (?, ?)";
А есть защита от дублирования лайка? Следующий комментарий как раз может помочь обойтись без нее

2023-04-19 17:55 UTC, dimabakinec commented on src/main/resources/application.properties
> +spring.sql.init.mode=alwaysspring.datasource.url=jdbc:h2:file:./db/filmoratespring.datasource.driverClassName=org.h2.Driverspring.datasource.username=saspring.datasource.password=password
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

у меня все вот так

2023-04-19 19:30 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        final String sql = "INSERT INTO popular_films (film_id, user_id) VALUES (?, ?)";
какой следующий комментарий?

2023-04-19 19:33 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        Map<Long, List<Genre>> listGenresByFilms = genreDbStorage.getGenreByFilm();
нужно менять или можно так оставить?

2023-04-19 19:34 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        Map<Long, List<Genre>> listGenresByFilms = genreDbStorage.getGenreByFilm();
что тут нужно сделать?

2023-04-19 19:46 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        final String sqlAddLike = "UPDATE films SET count_likes = count_likes + 1 WHERE film_id=?";
ок

2023-04-19 19:46 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public Map<Long, List<Genre>> getGenreByFilm() {
убрать метод и сделать новый?

2023-04-19 19:47 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/FilmMapper.java
> +        List<Genre> genres = listGenresByFilms.getOrDefault(rs.getLong("film_id"), new ArrayList<>());
а как нужно сделать?

2023-04-19 19:53 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        return find(data.getId());
убрал

2023-04-22 10:52 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        final String sql = "INSERT INTO popular_films (film_id, user_id) VALUES (?, ?)";
"Лучше запрашивать жанры по фильмам, которые мы получили нежели сохранять все жанры всех фильмов в эту мапу"

2023-04-22 11:26 UTC, alexache requested changes

2023-04-22 11:26 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDao.java
> +                throw new NotFoundException("Not found");
;опционально) зачем тогда Optional?

2023-04-22 11:26 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDao.java
> +            " LEFT JOIN FILM_GENRE FG on F.FILM_ID = FG.FILM_ID";
Эта строка лишняя?

2023-04-22 11:26 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeDbStorage.java
> +        final String sql = "INSERT INTO popular_films (film_id, user_id) VALUES (?, ?)";
"Эти ручные + - для подсчета количества лайков выглядят не очень надежно, можно ведь всегда одним запросом получить количество лайков для конкретного фильма на основен таблицы с лайками?"

2023-04-22 15:12 UTC, dimabakinec commented on .github/workflows/api-tests.yml
> -name: Films API Tests
удалил по ошибке, проверка ПР не пропускала и ругалась на лишние файлы проекте

2023-04-22 15:16 UTC, dimabakinec commented on .github/workflows/api-tests.yml
> -name: Films API Tests
вернул, теперь не могу пройти проверку ((

2023-04-22 15:17 UTC, dimabakinec commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +package ru.yandex.practicum.filmorate.controllers;
исправил

2023-04-23 10:13 UTC, dimabakinec commented on .github/workflows/api-tests.yml
> -name: Films API Tests
исправил, все проверки проходит

2023-04-24 08:56 UTC, alexache approved these changes

2023-04-24 08:57 UTC, merged